### ISSUE TITLE
uncompressed codec gives wrong colors for any YCbCr and RGB input

### ISSUE THREAD

**Issue by farindk** [strukturag/libheif#1267]
@bradh While working on #1242, I noticed that the uncompressed codec gives me wrong colors for basically all inputs I try. I tried YCbCr input from JPEGs and RGB from 8bit PNGs.

First, I thought this is because of my heavy refactoring, but I get the same output with v1.18.2.

I'm not attaching any test image here, because it fails with all color images I tried. If you need an image, let me know.

**Comment by farindk** [comment]
RGB data without alpha seems to be ok. But PNGs with alpha do not work correctly.

**Comment by bradh** [comment]
Is this on the encode side? Like `heif-enc --uncompressed something.png -o uncompressed.heif` ?

**Comment by farindk** [comment]
Difficult to say whether it's on the encoder side or decoder side. I can only do an `heif-enc` / `heif-dec` loop and the above picture comes out as
![out](https://github.com/user-attachments/assets/a03cf161-be7c-4d93-93e6-ea815fe5777a)

````
$ ./heif-enc with-alpha-512x513.png --uncompressed -o out.heif
$ ./heif-dec out.heif -o out.png
````

**Comment by bradh** [comment]
I can reproduce. The PNG + alpha problem looks like its on the decoder side, since gpac shows the encoded result correctly. The YCbCr problem looks like at least partly on the encoder side.

**Comment by bradh** [comment]
Should be resolved once both those PRs are merged.

**Comment by farindk** [comment]
Alpha output is still not working because `heif_image_handle_has_alpha_channel()` is not returning `true` for RGBA images. We need a way to determine this without actually decoding the image.

**Comment by farindk** [comment]
Alpha output of uncompressed RGBA works now. Also `heif-info` shows that there is an alpha channel.
