### ISSUE TITLE
10bit encoding with chroma=422 problem

### ISSUE THREAD

**Issue by novomesk** [strukturag/libheif#359]
Hello,
I tried encoding with YUV422 sub-sampling in libheif 1.9.1
When I use 16bit PNG as input, I notice following problem.

```
heif-enc -A -p chroma=422 -o yuv422.avif genessa16.png
heif-convert yuv422.avif yuv422.png
```
Original 16bit PNG genessa16.png :
![genessa16](https://user-images.githubusercontent.com/52529860/95860708-b7680080-0d60-11eb-9b94-e9fba6f05ca2.png)
Result yuv422.png :
![yuv422](https://user-images.githubusercontent.com/52529860/95860755-c8187680-0d60-11eb-97a6-8a79e0ef5333.png)

**Comment by farindk** [comment]
Top problem has been fixed by the patch from @Lynx3d in #348. Bottom problem partially fixed.
There still seems to be a colorspace issue.

**Comment by farindk** [comment]
@novomesk For your second example. If I encode as AVIF, everything is fine. However, when I use HEIF, I get the image below.
I have traced back the cause for this and found that I am asking x265 to write matrix_coefficients into the bitstream, but when I read back the matrix_coefficients, I get matrix_coefficients=2.
Since the image also has an ICC profile, the decoder has to rely on the information in the h265 bitstream. I'm not sure why the value of matrix_coefficients changes. I am using x265 version 2.6. Do you have the same problem?


![identity_test](https://user-images.githubusercontent.com/968944/97863371-26ed6200-1d07-11eb-9243-e525a6643478.png)

**Comment by farindk** [comment]
Fixed with https://github.com/strukturag/libde265/commit/60d682d77cabc3f9f383612e4f676b378b2e1f70
(Bug in reading h265 VUI header.)

**Comment by novomesk** [comment]
I am still experiencing this problem with matrix_coefficients=0, I have `x265 HEVC encoder (3.4)`

**Comment by farindk** [comment]
@novomesk See the comment above yours. I realized the bug is in the header parser of libde265 which tried to sanitize the input too much... You'll need a libde265 update. Then it should work.

**Comment by novomesk** [comment]
Sorry I overlooked that.
Using libde265 v1.0.8 helps!
Thanks for fixes and the clarification.
